/*
================================================================================
  001_create_tables.sql   (SQL Server / T-SQL)

  Creates:
    dbo.ImportBatches  - one row per imported Excel file (audit + counts)
    dbo.Transactions   - one row per Excel data row

  Design decisions
    * Primary key = (PayOrderNo, TxnRefSeqNo), both NOT NULL text.
    * Id (GUID) is a spare surrogate: unique, generated by the app, NOT the PK.
      If the real data turns out to have gaps/non-unique pairs, promote Id to
      the PK and demote the pair to a normal index.
    * RowHash = SHA-256 (hex) of the normalized business columns. Same key +
      same hash  -> exact duplicate (skip)
      Same key + different hash -> conflict (user decides)
    * Identifiers (account no, CNIC, refs...) are TEXT: Excel mixes numbers and
      strings, values can exceed INT range, and leading zeros must survive.
    * Amounts are DECIMAL(18,2).
    * Safe to re-run: every table is created only if it does not exist.

  Excel header -> column mapping (headers are matched after trimming/normalizing)
    Value Date            -> ValueDate
    Br. Code              -> BranchCode
    Branch Name           -> BranchName
    Reg No                -> RegNo
    Application no        -> ApplicationNo
    plot no               -> PlotNo
    Street No             -> StreetNo
    Challan No            -> ChallanNo
    Customer Name         -> CustomerName
    Cheque Inst. No.      -> ChequeInstNo
    CNIC No               -> Cnic
    payorder no           -> PayOrderNo        (PK part 1, required)
    Txn Ref/ Seq No       -> TxnRefSeqNo       (PK part 2, required)
    Discount              -> Discount
    Down payment Amount   -> DownPaymentAmount
    Debit                 -> Debit
    Credit                -> Credit
    Run. Bal              -> RunningBalance
    Bank Name             -> BankName
    Acct no               -> AccountNo
    Project               -> Project
    Delear Name  [sic]    -> DealerName
    Name of Data [sic]    -> DataSource
    Narraction 1 [sic]    -> Narration1
    Narration 2..5        -> Narration2..Narration5
================================================================================
*/

-- >>> Edit this line to your database name, or select it in your SQL tool <<<
-- USE [YourDatabaseName];

SET NOCOUNT ON;
SET XACT_ABORT ON;   -- any error rolls back the whole script

BEGIN TRANSACTION;

------------------------------------------------------------------------------
-- 1. ImportBatches
------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ImportBatches', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ImportBatches
    (
        Id            INT IDENTITY(1,1) NOT NULL,
        FileName      NVARCHAR(260)     NOT NULL,
        SheetName     NVARCHAR(100)     NULL,
        FileHash      CHAR(64)          NOT NULL,   -- SHA-256 hex; used for a "file already imported" WARNING, not a hard block
        ImportedAt    DATETIME2(0)      NOT NULL
                      CONSTRAINT DF_ImportBatches_ImportedAt DEFAULT SYSUTCDATETIME(),
        TotalRows     INT               NOT NULL CONSTRAINT DF_ImportBatches_TotalRows    DEFAULT 0,
        NewRows       INT               NOT NULL CONSTRAINT DF_ImportBatches_NewRows      DEFAULT 0,
        SkippedRows   INT               NOT NULL CONSTRAINT DF_ImportBatches_SkippedRows  DEFAULT 0,  -- exact duplicates
        UpdatedRows   INT               NOT NULL CONSTRAINT DF_ImportBatches_UpdatedRows  DEFAULT 0,  -- conflicts the user chose to overwrite
        RejectedRows  INT               NOT NULL CONSTRAINT DF_ImportBatches_RejectedRows DEFAULT 0,  -- invalid rows not imported

        CONSTRAINT PK_ImportBatches PRIMARY KEY CLUSTERED (Id),
        INDEX IX_ImportBatches_FileHash NONCLUSTERED (FileHash)
    );
END;

------------------------------------------------------------------------------
-- 2. Transactions
------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.Transactions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Transactions
    (
        -- Keys ---------------------------------------------------------------
        PayOrderNo        NVARCHAR(50)     NOT NULL,
        TxnRefSeqNo       NVARCHAR(50)     NOT NULL,
        Id                UNIQUEIDENTIFIER NOT NULL
                          CONSTRAINT DF_Transactions_Id DEFAULT NEWSEQUENTIALID(),  -- the app normally supplies its own

        -- Import tracking ----------------------------------------------------
        ImportBatchId     INT              NOT NULL,
        SourceRowNumber   INT              NULL,        -- Excel row number in the source file
        RowHash           CHAR(64)         NOT NULL,    -- SHA-256 hex of normalized business columns
        CreatedAt         DATETIME2(0)     NOT NULL
                          CONSTRAINT DF_Transactions_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt         DATETIME2(0)     NULL,        -- set when a conflict is overwritten

        -- Business columns ---------------------------------------------------
        ValueDate         DATE             NOT NULL,
        BranchCode        NVARCHAR(20)     NULL,
        BranchName        NVARCHAR(100)    NULL,
        RegNo             NVARCHAR(50)     NULL,
        ApplicationNo     NVARCHAR(50)     NULL,
        PlotNo            NVARCHAR(50)     NULL,
        StreetNo          NVARCHAR(50)     NULL,
        ChallanNo         NVARCHAR(50)     NULL,        -- repeats across rows; NOT unique
        ChequeInstNo      NVARCHAR(50)     NULL,
        CustomerName      NVARCHAR(200)    NULL,
        Cnic              VARCHAR(20)      NULL,        -- digits only, dashes stripped by the importer

        Discount          DECIMAL(18,2)    NULL,
        DownPaymentAmount DECIMAL(18,2)    NULL,
        Debit             DECIMAL(18,2)    NULL,
        Credit            DECIMAL(18,2)    NULL,
        RunningBalance    DECIMAL(18,2)    NULL,

        BankName          NVARCHAR(100)    NULL,
        AccountNo         NVARCHAR(50)     NULL,
        Project           NVARCHAR(100)    NULL,
        DealerName        NVARCHAR(100)    NULL,
        DataSource        NVARCHAR(100)    NULL,        -- Excel column "Name of Data"

        Narration1        NVARCHAR(500)    NULL,
        Narration2        NVARCHAR(500)    NULL,
        Narration3        NVARCHAR(500)    NULL,
        Narration4        NVARCHAR(500)    NULL,
        Narration5        NVARCHAR(500)    NULL,

        -- Constraints --------------------------------------------------------
        CONSTRAINT PK_Transactions PRIMARY KEY CLUSTERED (PayOrderNo, TxnRefSeqNo),
        CONSTRAINT UQ_Transactions_Id UNIQUE NONCLUSTERED (Id),
        CONSTRAINT FK_Transactions_ImportBatches
            FOREIGN KEY (ImportBatchId) REFERENCES dbo.ImportBatches (Id),

        -- Indexes for the filter screen --------------------------------------
        -- (PayOrderNo is already covered by the leading column of the PK)
        INDEX IX_Transactions_TxnRefSeqNo   NONCLUSTERED (TxnRefSeqNo),
        INDEX IX_Transactions_ValueDate     NONCLUSTERED (ValueDate),
        INDEX IX_Transactions_Bank_Account  NONCLUSTERED (BankName, AccountNo),
        INDEX IX_Transactions_Project       NONCLUSTERED (Project),
        INDEX IX_Transactions_DealerName    NONCLUSTERED (DealerName),
        INDEX IX_Transactions_CustomerName  NONCLUSTERED (CustomerName),
        INDEX IX_Transactions_Cnic          NONCLUSTERED (Cnic),
        INDEX IX_Transactions_ApplicationNo NONCLUSTERED (ApplicationNo),
        INDEX IX_Transactions_ChallanNo     NONCLUSTERED (ChallanNo),
        INDEX IX_Transactions_ImportBatchId NONCLUSTERED (ImportBatchId)
    );
END;

COMMIT TRANSACTION;

------------------------------------------------------------------------------
-- 3. Quick verification (read-only)
------------------------------------------------------------------------------
SELECT t.name AS TableName, COUNT(c.column_id) AS ColumnCount
FROM sys.tables AS t
JOIN sys.columns AS c ON c.object_id = t.object_id
WHERE t.name IN (N'ImportBatches', N'Transactions')
GROUP BY t.name;

SELECT OBJECT_NAME(i.object_id) AS TableName, i.name AS IndexName, i.type_desc, i.is_primary_key, i.is_unique
FROM sys.indexes AS i
WHERE OBJECT_NAME(i.object_id) IN (N'ImportBatches', N'Transactions')
  AND i.name IS NOT NULL
ORDER BY TableName, i.is_primary_key DESC, IndexName;

/*
-- ROLLBACK (development only: deletes all imported data!)
-- DROP TABLE IF EXISTS dbo.Transactions;
-- DROP TABLE IF EXISTS dbo.ImportBatches;
*/
